// Auto-generated by Antigravity
import { slides as allSlides } from './data/index.js';

export const slides = allSlides;

export function getSlideById(id) {
  return slides.find((slide) => slide.id === id);
}

export function getSlideByIndex(index) {
  return slides[index] || null;
}

export function getSlideCount() {
  return slides.length;
}
